project_id = "yxfdfxemywbufgtnkbfe"

[functions.wordpress-metrics]
verify_jwt = false

[functions.wordpress-categories]
verify_jwt = false

[functions.push-to-wordpress]
verify_jwt = false

[functions.generate-2fa-secret]
verify_jwt = false

[functions.verify-2fa]
verify_jwt = false

[functions.upload-wordpress-media]
verify_jwt = false